platform :osx, '10.14'

target 'PodProject' do
  # use_frameworks!
  pod 'ImmutableGraph', :path => '../'
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          if config.name == 'PodProject'
              config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'No'
          end
      end
  end
end