name: CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # enable manual execution

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage -v

    - name: Generate Codecov
      run: |
        /usr/lib/llvm-9/bin/llvm-cov export \
          -format="lcov" .build/x86_64-unknown-linux-gnu/debug/ImmutableGraphPackageTests.xctest \
          -instr-profile=.build/x86_64-unknown-linux-gnu/debug/codecov/default.profdata \
          > info.lcov
    - name: Print Codecov
      run: cat info.lcov
    - name: Upload to codecov.io
      run: bash <(curl -s https://codecov.io/bash) -f info.lcov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
